#
# This file is auto-generated. DO NOT MODIFY!  Run `make pystubs` to regenerate
#

"""OpenImageIO nanobind bindings."""

from collections.abc import Iterator, Sequence
import enum
import typing
from typing import ClassVar, overload

import numpy


class BASETYPE(enum.Enum):
    UNKNOWN = 0

    NONE = 1

    UCHAR = 2

    UINT8 = 2

    CHAR = 3

    INT8 = 3

    UINT16 = 4

    USHORT = 4

    SHORT = 5

    INT16 = 5

    UINT = 6

    UINT32 = 6

    INT = 7

    INT32 = 7

    ULONGLONG = 8

    UINT64 = 8

    LONGLONG = 9

    INT64 = 9

    HALF = 10

    FLOAT = 11

    DOUBLE = 12

    STRING = 13

    PTR = 14

    LASTBASE = 16

UNKNOWN: BASETYPE = BASETYPE.UNKNOWN

NONE: BASETYPE = BASETYPE.NONE

UCHAR: BASETYPE = BASETYPE.UCHAR

CHAR: BASETYPE = BASETYPE.CHAR

UINT16: BASETYPE = BASETYPE.UINT16

SHORT: BASETYPE = BASETYPE.SHORT

UINT: BASETYPE = BASETYPE.UINT

INT: BASETYPE = BASETYPE.INT

ULONGLONG: BASETYPE = BASETYPE.ULONGLONG

LONGLONG: BASETYPE = BASETYPE.LONGLONG

HALF: BASETYPE = BASETYPE.HALF

FLOAT: BASETYPE = BASETYPE.FLOAT

DOUBLE: BASETYPE = BASETYPE.DOUBLE

STRING: BASETYPE = BASETYPE.STRING

PTR: BASETYPE = BASETYPE.PTR

LASTBASE: BASETYPE = BASETYPE.LASTBASE

class AGGREGATE(enum.Enum):
    SCALAR = 1

    VEC2 = 2

    VEC3 = 3

    VEC4 = 4

    MATRIX33 = 9

    MATRIX44 = 16

SCALAR: AGGREGATE = AGGREGATE.SCALAR

VEC2: AGGREGATE = AGGREGATE.VEC2

VEC3: AGGREGATE = AGGREGATE.VEC3

VEC4: AGGREGATE = AGGREGATE.VEC4

MATRIX33: AGGREGATE = AGGREGATE.MATRIX33

MATRIX44: AGGREGATE = AGGREGATE.MATRIX44

class VECSEMANTICS(enum.Enum):
    NOXFORM = 0

    NOSEMANTICS = 0

    COLOR = 1

    POINT = 2

    VECTOR = 3

    NORMAL = 4

    TIMECODE = 5

    KEYCODE = 6

    RATIONAL = 7

    BOX = 8

NOXFORM: VECSEMANTICS = VECSEMANTICS.NOXFORM

COLOR: VECSEMANTICS = VECSEMANTICS.COLOR

POINT: VECSEMANTICS = VECSEMANTICS.POINT

VECTOR: VECSEMANTICS = VECSEMANTICS.VECTOR

NORMAL: VECSEMANTICS = VECSEMANTICS.NORMAL

TIMECODE: VECSEMANTICS = VECSEMANTICS.TIMECODE

KEYCODE: VECSEMANTICS = VECSEMANTICS.KEYCODE

RATIONAL: VECSEMANTICS = VECSEMANTICS.RATIONAL

BOX: VECSEMANTICS = VECSEMANTICS.BOX

class TypeDesc:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg: TypeDesc | BASETYPE | str, /) -> None: ...
    @overload
    def __init__(self, arg: BASETYPE, /) -> None: ...
    @overload
    def __init__(self, arg0: BASETYPE, arg1: AGGREGATE, /) -> None: ...
    @overload
    def __init__(self, arg0: BASETYPE, arg1: AGGREGATE, arg2: VECSEMANTICS, /) -> None: ...
    @overload
    def __init__(self, arg0: BASETYPE, arg1: AGGREGATE, arg2: VECSEMANTICS, arg3: int, /) -> None: ...
    @overload
    def __init__(self, arg: str, /) -> None: ...

    @property
    def basetype(self) -> BASETYPE: ...

    @basetype.setter
    def basetype(self, arg: BASETYPE, /) -> int: ...

    @property
    def aggregate(self) -> AGGREGATE: ...

    @aggregate.setter
    def aggregate(self, arg: AGGREGATE, /) -> int: ...

    @property
    def vecsemantics(self) -> VECSEMANTICS: ...

    @vecsemantics.setter
    def vecsemantics(self, arg: VECSEMANTICS, /) -> int: ...

    @property
    def arraylen(self) -> int: ...

    @arraylen.setter
    def arraylen(self, arg: int, /) -> None: ...

    def c_str(self) -> str: ...

    def numelements(self) -> int: ...

    def basevalues(self) -> int: ...

    def size(self) -> int: ...

    def elementtype(self) -> TypeDesc: ...

    def elementsize(self) -> int: ...

    def basesize(self) -> int: ...

    def fromstring(self, arg: str, /) -> None: ...

    def equivalent(self, arg: TypeDesc | BASETYPE | str, /) -> bool: ...

    def unarray(self) -> None: ...

    def is_vec2(self, b: BASETYPE = BASETYPE.FLOAT) -> bool: ...

    def is_vec3(self, b: BASETYPE = BASETYPE.FLOAT) -> bool: ...

    def is_vec4(self, b: BASETYPE = BASETYPE.FLOAT) -> bool: ...

    def is_box2(self, b: BASETYPE = BASETYPE.FLOAT) -> bool: ...

    def is_box3(self, b: BASETYPE = BASETYPE.FLOAT) -> bool: ...

    @staticmethod
    def all_types_equal(arg: Sequence[TypeDesc], /) -> bool: ...

    def __eq__(self, arg: object, /) -> bool: ...

    def __ne__(self, arg: object, /) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

UINT8: BASETYPE = BASETYPE.UCHAR

INT8: BASETYPE = BASETYPE.CHAR

USHORT: BASETYPE = BASETYPE.UINT16

INT16: BASETYPE = BASETYPE.SHORT

UINT32: BASETYPE = BASETYPE.UINT

INT32: BASETYPE = BASETYPE.INT

UINT64: BASETYPE = BASETYPE.ULONGLONG

INT64: BASETYPE = BASETYPE.LONGLONG

NOSEMANTICS: VECSEMANTICS = VECSEMANTICS.NOXFORM

TypeUnknown: TypeDesc = ...

TypeFloat: TypeDesc = ...

TypeColor: TypeDesc = ...

TypePoint: TypeDesc = ...

TypeVector: TypeDesc = ...

TypeNormal: TypeDesc = ...

TypeString: TypeDesc = ...

TypeInt: TypeDesc = ...

TypeUInt: TypeDesc = ...

TypeInt64: TypeDesc = ...

TypeUInt64: TypeDesc = ...

TypeInt32: TypeDesc = ...

TypeUInt32: TypeDesc = ...

TypeInt16: TypeDesc = ...

TypeUInt16: TypeDesc = ...

TypeInt8: TypeDesc = ...

TypeUInt8: TypeDesc = ...

TypeHalf: TypeDesc = ...

TypeMatrix: TypeDesc = ...

TypeMatrix33: TypeDesc = ...

TypeMatrix44: TypeDesc = ...

TypeTimeCode: TypeDesc = ...

TypeKeyCode: TypeDesc = ...

TypeFloat2: TypeDesc = ...

TypeVector2: TypeDesc = ...

TypeFloat4: TypeDesc = ...

TypeVector4: TypeDesc = ...

TypeVector2i: TypeDesc = ...

TypeVector3i: TypeDesc = ...

TypeBox2: TypeDesc = ...

TypeBox3: TypeDesc = ...

TypeBox2i: TypeDesc = ...

TypeBox3i: TypeDesc = ...

TypeRational: TypeDesc = ...

TypeURational: TypeDesc = ...

TypePointer: TypeDesc = ...

class Interp(enum.Enum):
    CONSTANT = 0

    PERPIECE = 1

    LINEAR = 2

    VERTEX = 3

    INTERP_CONSTANT = 0

    INTERP_PERPIECE = 1

    INTERP_LINEAR = 2

    INTERP_VERTEX = 3

class ParamValue:
    @overload
    def __init__(self, arg0: str, arg1: int, /) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: float, /) -> None: ...
    @overload
    def __init__(self, arg0: str, arg1: str, /) -> None: ...
    @overload
    def __init__(self, name: str, type: TypeDesc | BASETYPE | str, value: object) -> None: ...
    @overload
    def __init__(self, name: str, type: TypeDesc | BASETYPE | str, nvalues: int, interp: Interp, value: object) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> TypeDesc: ...

    @property
    def value(self) -> object: ...

    @property
    def __len__(self) -> int: ...

class ParamValueList:
    def __init__(self) -> None: ...

    @overload
    def __getitem__(self, arg: int, /) -> ParamValue: ...

    @overload
    def __getitem__(self, arg: str, /) -> object: ...

    def __setitem__(self, arg0: str, arg1: object, /) -> None: ...

    def __delitem__(self, arg: str, /) -> None: ...

    def __contains__(self, arg: str, /) -> bool: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> Iterator[ParamValue]: ...

    def append(self, arg: ParamValue, /) -> None: ...

    def clear(self) -> None: ...

    def free(self) -> None: ...

    def resize(self, arg: int, /) -> None: ...

    def remove(self, name: str, type: TypeDesc | BASETYPE | str = ..., casesensitive: bool = True) -> None: ...

    def contains(self, name: str, type: TypeDesc | BASETYPE | str = ..., casesensitive: bool = True) -> bool: ...

    def add_or_replace(self, value: ParamValue, casesensitive: bool = True) -> None: ...

    def sort(self, casesensitive: bool = True) -> None: ...

    def merge(self, other: ParamValueList, override: bool = False) -> None: ...

    @overload
    def attribute(self, name: str, val: object) -> None: ...
    @overload
    def attribute(self, arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: object, /) -> None: ...
    @overload
    def attribute(self, arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: int, arg3: object, /) -> None: ...

class ImageSpec:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: TypeDesc | BASETYPE | str, /) -> None: ...
    @overload
    def __init__(self, arg0: ROI, arg1: TypeDesc | BASETYPE | str, /) -> None: ...
    @overload
    def __init__(self, arg: TypeDesc | BASETYPE | str, /) -> None: ...
    @overload
    def __init__(self, arg: ImageSpec) -> None: ...

    @property
    def x(self) -> int: ...

    @x.setter
    def x(self, arg: int, /) -> None: ...

    @property
    def y(self) -> int: ...

    @y.setter
    def y(self, arg: int, /) -> None: ...

    @property
    def z(self) -> int: ...

    @z.setter
    def z(self, arg: int, /) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def depth(self) -> int: ...

    @depth.setter
    def depth(self, arg: int, /) -> None: ...

    @property
    def full_x(self) -> int: ...

    @full_x.setter
    def full_x(self, arg: int, /) -> None: ...

    @property
    def full_y(self) -> int: ...

    @full_y.setter
    def full_y(self, arg: int, /) -> None: ...

    @property
    def full_z(self) -> int: ...

    @full_z.setter
    def full_z(self, arg: int, /) -> None: ...

    @property
    def full_width(self) -> int: ...

    @full_width.setter
    def full_width(self, arg: int, /) -> None: ...

    @property
    def full_height(self) -> int: ...

    @full_height.setter
    def full_height(self, arg: int, /) -> None: ...

    @property
    def full_depth(self) -> int: ...

    @full_depth.setter
    def full_depth(self, arg: int, /) -> None: ...

    @property
    def tile_width(self) -> int: ...

    @tile_width.setter
    def tile_width(self, arg: int, /) -> None: ...

    @property
    def tile_height(self) -> int: ...

    @tile_height.setter
    def tile_height(self, arg: int, /) -> None: ...

    @property
    def tile_depth(self) -> int: ...

    @tile_depth.setter
    def tile_depth(self, arg: int, /) -> None: ...

    @property
    def nchannels(self) -> int: ...

    @nchannels.setter
    def nchannels(self, arg: int, /) -> None: ...

    @overload
    def format(self) -> TypeDesc: ...
    @overload
    def format(self, arg: TypeDesc | BASETYPE | str, /) -> None: ...

    @property
    def channelformats(self) -> tuple: ...

    @channelformats.setter
    def channelformats(self, arg: object, /) -> None: ...

    @property
    def channelnames(self) -> tuple: ...

    @channelnames.setter
    def channelnames(self, arg: object, /) -> None: ...

    @property
    def alpha_channel(self) -> int: ...

    @alpha_channel.setter
    def alpha_channel(self, arg: int, /) -> None: ...

    @property
    def z_channel(self) -> int: ...

    @z_channel.setter
    def z_channel(self, arg: int, /) -> None: ...

    @property
    def deep(self) -> bool: ...

    @deep.setter
    def deep(self, arg: bool, /) -> None: ...

    @property
    def extra_attribs(self) -> ParamValueList: ...

    @extra_attribs.setter
    def extra_attribs(self, arg: ParamValueList, /) -> None: ...

    @property
    def roi(self) -> ROI: ...

    @roi.setter
    def roi(self, arg: ROI, /) -> None: ...

    @property
    def roi_full(self) -> ROI: ...

    @roi_full.setter
    def roi_full(self, arg: ROI, /) -> None: ...

    def copy(self) -> ImageSpec: ...

    def set_format(self, arg: TypeDesc | BASETYPE | str, /) -> None: ...

    def default_channel_names(self) -> None: ...

    @overload
    def channel_bytes(self) -> int: ...

    @overload
    def channel_bytes(self, channel: int, native: bool = False) -> int: ...

    @overload
    def pixel_bytes(self, native: bool = False) -> int: ...

    @overload
    def pixel_bytes(self, chbegin: int, chend: int, native: bool = False) -> int: ...

    @overload
    def scanline_bytes(self, native: bool = False) -> int: ...
    @overload
    def scanline_bytes(self, arg: TypeDesc | BASETYPE | str, /) -> int: ...

    @overload
    def tile_bytes(self, native: bool = False) -> int: ...
    @overload
    def tile_bytes(self, arg: TypeDesc | BASETYPE | str, /) -> int: ...

    @overload
    def image_bytes(self, native: bool = False) -> int: ...
    @overload
    def image_bytes(self, native: TypeDesc | BASETYPE | str = ...) -> int: ...

    def tile_pixels(self) -> int: ...

    def image_pixels(self) -> int: ...

    def size_t_safe(self) -> bool: ...

    def channelformat(self, arg: int, /) -> TypeDesc: ...

    def channel_name(self, arg: int, /) -> str: ...

    def channelindex(self, arg: str, /) -> int: ...

    def get_channelformats(self) -> tuple[TypeDesc, ...]: ...

    @overload
    def attribute(self, arg0: str, arg1: object, /) -> None: ...
    @overload
    def attribute(self, arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: object, /) -> None: ...

    def get_int_attribute(self, name: str, defaultval: int = 0) -> int: ...

    def get_float_attribute(self, name: str, defaultval: float = 0.0) -> float: ...

    def get_string_attribute(self, name: str, defaultval: str = '') -> str: ...

    def get_bytes_attribute(self, name: str, defaultval: str = '') -> bytes: ...

    def getattribute(self, name: str, type: TypeDesc | BASETYPE | str = ...) -> typing.Any: ...

    def get(self, key: str, default: object | None = None) -> typing.Any: ...

    def erase_attribute(self, name: str = '', type: TypeDesc | BASETYPE | str = ..., casesensitive: bool = False) -> None: ...

    @staticmethod
    def metadata_val(param: ParamValue, human: bool = False) -> str: ...

    def serialize(self, format: str = 'text', verbose: str = 'detailed') -> str: ...

    def to_xml(self) -> str: ...

    def from_xml(self, arg: str, /) -> None: ...

    def valid_tile_range(self, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int = 0, zend: int = 1) -> bool: ...

    def copy_dimensions(self, other: ImageSpec) -> None: ...

    def set_colorspace(self, name: str) -> None: ...

    def __getitem__(self, arg: str, /) -> object: ...

    def __setitem__(self, arg0: str, arg1: object, /) -> None: ...

    def __delitem__(self, arg: str, /) -> None: ...

    def __contains__(self, arg: str, /) -> bool: ...

class ROI:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, /) -> None: ...

    @overload
    def __init__(self, arg: ROI) -> None: ...

    @property
    def xbegin(self) -> int: ...

    @xbegin.setter
    def xbegin(self, arg: int, /) -> None: ...

    @property
    def xend(self) -> int: ...

    @xend.setter
    def xend(self, arg: int, /) -> None: ...

    @property
    def ybegin(self) -> int: ...

    @ybegin.setter
    def ybegin(self, arg: int, /) -> None: ...

    @property
    def yend(self) -> int: ...

    @yend.setter
    def yend(self, arg: int, /) -> None: ...

    @property
    def zbegin(self) -> int: ...

    @zbegin.setter
    def zbegin(self, arg: int, /) -> None: ...

    @property
    def zend(self) -> int: ...

    @zend.setter
    def zend(self, arg: int, /) -> None: ...

    @property
    def chbegin(self) -> int: ...

    @chbegin.setter
    def chbegin(self, arg: int, /) -> None: ...

    @property
    def chend(self) -> int: ...

    @chend.setter
    def chend(self, arg: int, /) -> None: ...

    @property
    def defined(self) -> bool: ...

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def depth(self) -> int: ...

    @property
    def nchannels(self) -> int: ...

    @property
    def npixels(self) -> int: ...

    @overload
    def contains(self, x: int, y: int, z: int = 0, ch: int = 0) -> bool: ...

    @overload
    def contains(self, other: ROI) -> bool: ...

    All: ClassVar[ROI] = ...  # read-only

    def __str__(self) -> str: ...

    def copy(self) -> ROI: ...

    def __eq__(self, arg: object, /) -> bool: ...

    def __ne__(self, arg: object, /) -> bool: ...

def union(arg0: ROI, arg1: ROI, /) -> ROI: ...

def intersection(arg0: ROI, arg1: ROI, /) -> ROI: ...

def get_roi(arg: ImageSpec, /) -> ROI: ...

def get_roi_full(arg: ImageSpec, /) -> ROI: ...

def set_roi(arg0: ImageSpec, arg1: ROI, /) -> None: ...

def set_roi_full(arg0: ImageSpec, arg1: ROI, /) -> None: ...

class DeepData:
    def __init__(self) -> None: ...

    @property
    def pixels(self) -> int: ...

    @property
    def channels(self) -> int: ...

    @property
    def A_channel(self) -> int: ...

    @property
    def AR_channel(self) -> int: ...

    @property
    def AG_channel(self) -> int: ...

    @property
    def AB_channel(self) -> int: ...

    @property
    def Z_channel(self) -> int: ...

    @property
    def Zback_channel(self) -> int: ...

    @overload
    def init(self, npixels: int, nchannels: int, channeltypes: object, channelnames: object) -> None: ...

    @overload
    def init(self, arg: ImageSpec, /) -> None: ...

    def clear(self) -> None: ...

    def free(self) -> None: ...

    def initialized(self) -> bool: ...

    def allocated(self) -> bool: ...

    def samples(self, pixel: int) -> int: ...

    def set_samples(self, pixel: int, nsamples: int) -> None: ...

    def capacity(self, pixel: int) -> int: ...

    def set_capacity(self, pixel: int, nsamples: int) -> None: ...

    def insert_samples(self, pixel: int, samplepos: int, nsamples: int = 1) -> None: ...

    def erase_samples(self, pixel: int, samplepos: int, nsamples: int = 1) -> None: ...

    def channelname(self, arg: int, /) -> str: ...

    def channeltype(self, arg: int, /) -> TypeDesc: ...

    def channelsize(self, arg: int, /) -> int: ...

    def same_channeltypes(self, arg: DeepData, /) -> bool: ...

    def samplesize(self) -> int: ...

    def deep_value(self, pixel: int, channel: int, sample: int) -> float: ...

    def deep_value_uint(self, pixel: int, channel: int, sample: int) -> int: ...

    def set_deep_value(self, pixel: int, channel: int, sample: int, value: float) -> None: ...

    def set_deep_value_uint(self, pixel: int, channel: int, sample: int, value: int) -> None: ...

    def copy_deep_sample(self, pixel: int, sample: int, src: DeepData, srcpixel: int, srcsample: int) -> bool: ...

    def copy_deep_pixel(self, pixel: int, src: DeepData, srcpixel: int) -> bool: ...

    def split(self, pixel: int, depth: float) -> bool: ...

    def sort(self, pixel: int) -> None: ...

    def merge_overlaps(self, pixel: int) -> None: ...

    def merge_deep_pixels(self, pixel: int, src: DeepData, srcpixel: int) -> bool: ...

    def occlusion_cull(self, pixel: int) -> None: ...

    def opaque_z(self, pixel: int) -> float: ...

class ColorConfig:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: str, /) -> None: ...

    def geterror(self) -> str: ...

    def getNumColorSpaces(self) -> int: ...

    def getColorSpaceNames(self) -> list[str]: ...

    def getColorSpaceNameByIndex(self, arg: int, /) -> str: ...

    def getColorSpaceIndex(self, name: str) -> int: ...

    def getColorSpaceNameByRole(self, role: str) -> str: ...

    def getNumRoles(self) -> int: ...

    def getRoleByIndex(self, arg: int, /) -> str: ...

    def getRoles(self) -> list[str]: ...

    def getColorSpaceDataType(self, name: str) -> tuple[TypeDesc, int]: ...

    def getColorSpaceFamilyByName(self, name: str) -> str: ...

    def getNumLooks(self) -> int: ...

    def getLookNameByIndex(self, arg: int, /) -> str: ...

    def getLookNames(self) -> list[str]: ...

    def getNumDisplays(self) -> int: ...

    def getDisplayNameByIndex(self, arg: int, /) -> str: ...

    def getDisplayNames(self) -> list[str]: ...

    def getDefaultDisplayName(self) -> str: ...

    def getNumViews(self, display: str = '') -> int: ...

    def getViewNameByIndex(self, display: str = '', index: int = 0) -> str: ...

    def getViewNames(self, display: str = '') -> list[str]: ...

    def getDefaultViewName(self, display: str = '', input_color_space: str = '') -> str: ...

    def getDisplayViewColorSpaceName(self, display: str, view: str) -> str: ...

    def getDisplayViewLooks(self, display: str, view: str) -> str: ...

    def getAliases(self, arg: str, /) -> list[str]: ...

    def getNumNamedTransforms(self) -> int: ...

    def getNamedTransformNameByIndex(self, arg: int, /) -> str: ...

    def getNamedTransformNames(self) -> list[str]: ...

    def getNamedTransformAliases(self, arg: str, /) -> list[str]: ...

    def isColorSpaceLinear(self, name: str) -> bool: ...

    def isData(self, name: str) -> bool: ...

    def isColorSpaceActive(self, name: str) -> bool: ...

    @overload
    def getColorSpaceFromFilepath(self, filepath: str) -> str: ...

    @overload
    def getColorSpaceFromFilepath(self, filepath: str, default_cs: str, cs_name_match: bool = False) -> str: ...

    def filepathOnlyMatchesDefaultRule(self, filepath: str) -> bool: ...

    def parseColorSpaceFromString(self, arg: str, /) -> str: ...

    def resolve(self, name: str) -> str: ...

    def equivalent(self, color_space: str, other_color_space: str) -> bool: ...

    @overload
    def get_color_interop_id(self, arg: str, /) -> str: ...

    @overload
    def get_color_interop_id(self, arg: Sequence[int], /) -> str: ...

    def get_cicp(self, arg: str, /) -> list[int] | None: ...

    def configname(self) -> str: ...

    @staticmethod
    def default_colorconfig() -> ColorConfig: ...

supportsOpenColorIO: bool = True

OpenColorIO_version_hex: int = 33882368

class ImageInput:
    @staticmethod
    def create(filename: str, plugin_searchpath: str = '') -> ImageInput | None: ...

    @overload
    @staticmethod
    def open(filename: str) -> ImageInput | None: ...
    @overload
    @staticmethod
    def open(filename: str, config: ImageSpec) -> ImageInput | None: ...

    def format_name(self) -> str: ...

    def valid_file(self, arg: str, /) -> bool: ...

    @overload
    def spec(self) -> ImageSpec: ...

    @overload
    def spec(self, subimage: int, miplevel: int = 0) -> ImageSpec: ...

    def spec_dimensions(self, subimage: int, miplevel: int = 0) -> ImageSpec: ...

    def supports(self, arg: str, /) -> int: ...

    def close(self) -> bool: ...

    def current_subimage(self) -> int: ...

    def current_miplevel(self) -> int: ...

    def seek_subimage(self, arg0: int, arg1: int, /) -> bool: ...

    @overload
    def read_image(self, subimage: int, miplevel: int, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...
    @overload
    def read_image(self, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...
    @overload
    def read_image(self, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    def read_scanline(self, y: int, z: int = 0, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    @overload
    def read_scanlines(self, subimage: int, miplevel: int, ybegin: int, yend: int, z: int, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...
    @overload
    def read_scanlines(self, ybegin: int, yend: int, z: int, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    @overload
    def read_tiles(self, subimage: int, miplevel: int, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int, zend: int, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...
    @overload
    def read_tiles(self, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int, zend: int, chbegin: int, chend: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    def read_tile(self, x: int, y: int, z: int, format: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    def read_native_deep_scanlines(self, subimage: int, miplevel: int, ybegin: int, yend: int, z: int, chbegin: int, chend: int) -> DeepData | None: ...

    def read_native_deep_tiles(self, subimage: int, miplevel: int, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int, zend: int, chbegin: int, chend: int) -> DeepData | None: ...

    def read_native_deep_image(self, subimage: int = 0, miplevel: int = 0) -> DeepData | None: ...

    def get_thumbnail(self, subimage: int = 0) -> ImageBuf: ...

    @property
    def has_error(self) -> bool: ...

    def geterror(self, clear: bool = True) -> str: ...

class ImageOutput:
    @staticmethod
    def create(filename: str, plugin_searchpath: str = '') -> ImageOutput | None: ...

    def format_name(self) -> str: ...

    def supports(self, arg: str, /) -> int: ...

    def spec(self) -> ImageSpec: ...

    @overload
    def open(self, filename: str, spec: ImageSpec, mode: str = 'Create') -> bool: ...

    @overload
    def open(self, filename: str, specs: Sequence[ImageSpec]) -> bool: ...

    @overload
    def open(self, arg0: str, arg1: tuple, /) -> bool: ...

    def close(self) -> bool: ...

    def write_image(self, arg: object, /) -> bool: ...

    def write_scanline(self, y: int, z: int, pixels: object) -> bool: ...

    def write_scanlines(self, ybegin: int, yend: int, z: int, pixels: object) -> bool: ...

    def write_tile(self, x: int, y: int, z: int, pixels: object) -> bool: ...

    def write_tiles(self, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int, zend: int, pixels: object) -> bool: ...

    def write_deep_scanlines(self, ybegin: int, yend: int, z: int, deepdata: DeepData) -> bool: ...

    def write_deep_tiles(self, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int, zend: int, deepdata: DeepData) -> bool: ...

    def write_deep_image(self, arg: DeepData, /) -> bool: ...

    def set_thumbnail(self, arg: ImageBuf, /) -> bool: ...

    def copy_image(self, arg: ImageInput, /) -> bool: ...

    @property
    def has_error(self) -> bool: ...

    def geterror(self, clear: bool = True) -> str: ...

class ImageBuf:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: str, /) -> None: ...

    @overload
    def __init__(self, arg0: str, arg1: int, arg2: int, /) -> None: ...

    @overload
    def __init__(self, arg: ImageSpec, /) -> None: ...

    @overload
    def __init__(self, spec: ImageSpec, zero: bool) -> None: ...

    @overload
    def __init__(self, name: str, subimage: int, miplevel: int, config: ImageSpec) -> None: ...

    @overload
    def __init__(self, buffer: object) -> None: ...

    def clear(self) -> None: ...

    @overload
    def reset(self, name: str, subimage: int = 0, miplevel: int = 0) -> None: ...

    @overload
    def reset(self, name: str, subimage: int = 0, miplevel: int = 0, config: ImageSpec = ...) -> None: ...

    @overload
    def reset(self, spec: ImageSpec, zero: bool = True) -> None: ...

    @overload
    def reset(self, buffer: object) -> None: ...

    @property
    def initialized(self) -> bool: ...

    def init_spec(self, filename: str, subimage: int = 0, miplevel: int = 0) -> bool: ...

    @overload
    def read(self, subimage: int, miplevel: int, chbegin: int, chend: int, force: bool, convert: TypeDesc | BASETYPE | str) -> bool: ...
    @overload
    def read(self, subimage: int = 0, miplevel: int = 0, force: bool = False, convert: TypeDesc | BASETYPE | str = ...) -> bool: ...

    @overload
    def write(self, filename: str, dtype: TypeDesc | BASETYPE | str = ..., fileformat: str = '') -> bool: ...
    @overload
    def write(self, out: ImageOutput) -> bool: ...

    def make_writable(self, keep_cache_type: bool = False) -> bool: ...

    def set_write_format(self, arg: object, /) -> None: ...

    def set_write_tiles(self, width: int = 0, height: int = 0, depth: int = 0) -> None: ...

    def spec(self) -> ImageSpec: ...

    def nativespec(self) -> ImageSpec: ...

    def specmod(self) -> ImageSpec: ...

    @property
    def has_thumbnail(self) -> bool: ...

    def clear_thumbnail(self) -> None: ...

    def set_thumbnail(self, thumb: ImageBuf) -> None: ...

    def get_thumbnail(self) -> ImageBuf: ...

    @property
    def name(self) -> str: ...

    @property
    def file_format_name(self) -> str: ...

    @property
    def subimage(self) -> int: ...

    @property
    def nsubimages(self) -> int: ...

    @property
    def miplevel(self) -> int: ...

    @property
    def nmiplevels(self) -> int: ...

    @property
    def nchannels(self) -> int: ...

    @property
    def orientation(self) -> int: ...

    @orientation.setter
    def orientation(self, arg: int, /) -> None: ...

    @property
    def oriented_width(self) -> int: ...

    @property
    def oriented_height(self) -> int: ...

    @property
    def oriented_x(self) -> int: ...

    @property
    def oriented_y(self) -> int: ...

    @property
    def oriented_full_width(self) -> int: ...

    @property
    def oriented_full_height(self) -> int: ...

    @property
    def oriented_full_x(self) -> int: ...

    @property
    def oriented_full_y(self) -> int: ...

    @property
    def xbegin(self) -> int: ...

    @property
    def xend(self) -> int: ...

    @property
    def ybegin(self) -> int: ...

    @property
    def yend(self) -> int: ...

    @property
    def zbegin(self) -> int: ...

    @property
    def zend(self) -> int: ...

    @property
    def xmin(self) -> int: ...

    @property
    def xmax(self) -> int: ...

    @property
    def ymin(self) -> int: ...

    @property
    def ymax(self) -> int: ...

    @property
    def zmin(self) -> int: ...

    @property
    def zmax(self) -> int: ...

    @property
    def roi(self) -> ROI: ...

    @property
    def roi_full(self) -> ROI: ...

    @roi_full.setter
    def roi_full(self, arg: ROI, /) -> None: ...

    def set_origin(self, x: int, y: int, z: int = 0) -> None: ...

    def set_full(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int, arg5: int, /) -> None: ...

    @property
    def pixels_valid(self) -> bool: ...

    @property
    def pixeltype(self) -> TypeDesc: ...

    @property
    def has_error(self) -> bool: ...

    def geterror(self, clear: bool = True) -> str: ...

    def pixelindex(self, x: int, y: int, z: int, check_range: bool = False) -> int: ...

    @overload
    def copy(self, src: ImageBuf, format: TypeDesc | BASETYPE | str = ...) -> bool: ...
    @overload
    def copy(self, format: TypeDesc | BASETYPE | str = ...) -> ImageBuf: ...

    def copy_pixels(self, arg: ImageBuf, /) -> bool: ...

    def copy_metadata(self, arg: ImageBuf, /) -> None: ...

    def merge_metadata(self, src: ImageBuf, override: bool = False, pattern: str = '') -> None: ...

    def swap(self, arg: ImageBuf, /) -> None: ...

    def getchannel(self, x: int, y: int, z: int, c: int, wrap: str = 'black') -> float: ...

    def getpixel(self, x: int, y: int, z: int = 0, wrap: str = 'black') -> tuple[float, ...]: ...

    def interppixel(self, x: float, y: float, wrap: str = 'black') -> tuple[float, ...]: ...

    def interppixel_NDC(self, x: float, y: float, wrap: str = 'black') -> tuple[float, ...]: ...

    def interppixel_NDC_full(self, x: float, y: float, wrap: str = 'black') -> tuple[float, ...]: ...

    def interppixel_bicubic(self, x: float, y: float, wrap: str = 'black') -> tuple[float, ...]: ...

    def interppixel_bicubic_NDC(self, x: float, y: float, wrap: str = 'black') -> tuple[float, ...]: ...

    @overload
    def setpixel(self, x: int, y: int, z: int, pixel: object) -> None: ...

    @overload
    def setpixel(self, x: int, y: int, pixel: object) -> None: ...

    @overload
    def setpixel(self, i: int, pixel: object) -> None: ...

    def get_pixels(self, format: TypeDesc | BASETYPE | str = ..., roi: ROI = ...) -> numpy.ndarray | None: ...

    def set_pixels(self, roi: ROI, pixels: object) -> bool: ...

    @property
    def deep(self) -> bool: ...

    def deep_samples(self, x: int, y: int, z: int = 0) -> int: ...

    def set_deep_samples(self, x: int, y: int, z: int = 0, nsamples: int = 1) -> None: ...

    def deep_insert_samples(self, x: int, y: int, z: int = 0, samplepos: int = 0, nsamples: int = 1) -> None: ...

    def deep_erase_samples(self, x: int, y: int, z: int = 0, samplepos: int = 0, nsamples: int = 1) -> None: ...

    def deep_value(self, x: int, y: int, z: int, channel: int, sample: int) -> float: ...

    def deep_value_uint(self, x: int, y: int, z: int, channel: int, sample: int) -> int: ...

    def set_deep_value(self, x: int, y: int, z: int, channel: int, sample: int, value: float = 0.0) -> None: ...

    def set_deep_value_uint(self, x: int, y: int, z: int, channel: int, sample: int, value: int = 0) -> None: ...

    def deepdata(self) -> DeepData: ...

class ImageCache:
    def __init__(self, shared: bool = True) -> None: ...

    @staticmethod
    def destroy(cache: ImageCache, teardown: bool = False) -> None: ...

    @overload
    def attribute(self, arg0: str, arg1: object, /) -> None: ...
    @overload
    def attribute(self, arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: object, /) -> None: ...

    def getattribute(self, name: str, type: TypeDesc | BASETYPE | str = ...) -> typing.Any: ...

    def getattributetype(self, name: str) -> TypeDesc: ...

    def resolve_filename(self, arg: str, /) -> str: ...

    def get_imagespec(self, filename: str, subimage: int = 0) -> ImageSpec: ...

    def get_cache_dimensions(self, filename: str, subimage: int = 0, miplevel: int = 0) -> ImageSpec: ...

    @overload
    def get_pixels(self, filename: str, subimage: int, miplevel: int, xbegin: int, xend: int, ybegin: int, yend: int, zbegin: int = 0, zend: int = 1, datatype: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...
    @overload
    def get_pixels(self, filename: str, subimage: int, miplevel: int, roi: ROI, datatype: TypeDesc | BASETYPE | str = ...) -> numpy.ndarray | None: ...

    @property
    def has_error(self) -> bool: ...

    def geterror(self, clear: bool = True) -> str: ...

    def getstats(self, level: int = 1) -> str: ...

    def invalidate(self, filename: str, force: bool = True) -> None: ...

    def invalidate_all(self, force: bool = False) -> None: ...

class Wrap(enum.Enum):
    Default = 0

    Black = 1

    Clamp = 2

    Periodic = 3

    Mirror = 4

    PeriodicPow2 = 5

    PeriodicSharedBorder = 6

    Last = 7

class MipMode(enum.Enum):
    Default = 0

    NoMIP = 1

    OneLevel = 2

    Trilinear = 3

    Aniso = 4

class InterpMode(enum.Enum):
    Closest = 0

    Bilinear = 1

    Bicubic = 2

    SmartBicubic = 3

class TextureOpt:
    def __init__(self) -> None: ...

    @property
    def firstchannel(self) -> int: ...

    @firstchannel.setter
    def firstchannel(self, arg: int, /) -> None: ...

    @property
    def subimage(self) -> int: ...

    @subimage.setter
    def subimage(self, arg: int, /) -> None: ...

    @property
    def subimagename(self) -> str: ...

    @subimagename.setter
    def subimagename(self, arg: str, /) -> None: ...

    @property
    def swrap(self) -> Wrap: ...

    @swrap.setter
    def swrap(self, arg: Wrap, /) -> None: ...

    @property
    def twrap(self) -> Wrap: ...

    @twrap.setter
    def twrap(self, arg: Wrap, /) -> None: ...

    @property
    def mipmode(self) -> MipMode: ...

    @mipmode.setter
    def mipmode(self, arg: MipMode, /) -> None: ...

    @property
    def interpmode(self) -> InterpMode: ...

    @interpmode.setter
    def interpmode(self, arg: InterpMode, /) -> None: ...

    @property
    def anisotropic(self) -> int: ...

    @anisotropic.setter
    def anisotropic(self, arg: int, /) -> None: ...

    @property
    def conservative_filter(self) -> bool: ...

    @conservative_filter.setter
    def conservative_filter(self, arg: bool, /) -> None: ...

    @property
    def sblur(self) -> float: ...

    @sblur.setter
    def sblur(self, arg: float, /) -> None: ...

    @property
    def tblur(self) -> float: ...

    @tblur.setter
    def tblur(self, arg: float, /) -> None: ...

    @property
    def swidth(self) -> float: ...

    @swidth.setter
    def swidth(self, arg: float, /) -> None: ...

    @property
    def twidth(self) -> float: ...

    @twidth.setter
    def twidth(self, arg: float, /) -> None: ...

    @property
    def fill(self) -> float: ...

    @fill.setter
    def fill(self, arg: float, /) -> None: ...

    @property
    def missingcolor(self) -> tuple: ...

    @missingcolor.setter
    def missingcolor(self, arg: object | None) -> None: ...

    @property
    def rnd(self) -> float: ...

    @rnd.setter
    def rnd(self, arg: float, /) -> None: ...

    @property
    def rwrap(self) -> Wrap: ...

    @rwrap.setter
    def rwrap(self, arg: Wrap, /) -> None: ...

    @property
    def rwidth(self) -> float: ...

    @rwidth.setter
    def rwidth(self, arg: float, /) -> None: ...

class TextureSystem:
    def __init__(self, shared: bool = True) -> None: ...

    @staticmethod
    def destroy(arg: TextureSystem, /) -> None: ...

    @overload
    def attribute(self, arg0: str, arg1: object, /) -> None: ...
    @overload
    def attribute(self, arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: object, /) -> None: ...

    def getattributetype(self, name: str) -> TypeDesc: ...

    def getattribute(self, name: str, type: TypeDesc | BASETYPE | str = ...) -> typing.Any: ...

    def texture(self, filename: str, options: TextureOpt, s: float, t: float, dsdx: float, dtdx: float, dsdy: float, dtdy: float, nchannels: int) -> tuple[float, ...]: ...

    def texture3d(self, filename: str, options: TextureOpt, P: Sequence[float], dPdx: Sequence[float], dPdy: Sequence[float], dPdz: Sequence[float], nchannels: int) -> tuple[float, ...]: ...

    def environment(self, filename: str, options: TextureOpt, R: Sequence[float], dRdx: Sequence[float], dRdy: Sequence[float], nchannels: int) -> tuple[float, ...]: ...

    def resolve_filename(self, filename: str) -> str: ...

    def imagespec(self, filename: str, subimage: int = 0) -> ImageSpec | None: ...

    def is_udim(self, filename: str) -> bool: ...

    def resolve_udim(self, filename: str, s: float, t: float) -> str: ...

    def inventory_udim(self, filename: str) -> tuple: ...

    def invalidate(self, filename: str, force: bool = True) -> None: ...

    def invalidate_all(self, force: bool = True) -> None: ...

    def close(self, filename: str) -> None: ...

    def close_all(self) -> None: ...

    def has_error(self) -> bool: ...

    def geterror(self, clear: bool = True) -> str: ...

    def getstats(self, level: int = 1, icstats: bool = True) -> str: ...

    def reset_stats(self) -> None: ...

class NonFiniteFixMode(enum.Enum):
    NONFINITE_NONE = 0

    NONFINITE_BLACK = 1

    NONFINITE_BOX3 = 2

NONFINITE_NONE: NonFiniteFixMode = NonFiniteFixMode.NONFINITE_NONE

NONFINITE_BLACK: NonFiniteFixMode = NonFiniteFixMode.NONFINITE_BLACK

NONFINITE_BOX3: NonFiniteFixMode = NonFiniteFixMode.NONFINITE_BOX3

class MakeTextureMode(enum.Enum):
    MakeTxTexture = 0

    MakeTxShadow = 1

    MakeTxEnvLatl = 2

    MakeTxEnvLatlFromLightProbe = 3

    MakeTxBumpWithSlopes = 4

MakeTxTexture: MakeTextureMode = MakeTextureMode.MakeTxTexture

MakeTxShadow: MakeTextureMode = MakeTextureMode.MakeTxShadow

MakeTxEnvLatl: MakeTextureMode = MakeTextureMode.MakeTxEnvLatl

MakeTxEnvLatlFromLightProbe: MakeTextureMode = MakeTextureMode.MakeTxEnvLatlFromLightProbe

MakeTxBumpWithSlopes: MakeTextureMode = MakeTextureMode.MakeTxBumpWithSlopes

class PixelStats:
    def __init__(self) -> None: ...

    @property
    def min(self) -> list[float]: ...

    @property
    def max(self) -> list[float]: ...

    @property
    def avg(self) -> list[float]: ...

    @property
    def stddev(self) -> list[float]: ...

    @property
    def nancount(self) -> list[int]: ...

    @property
    def infcount(self) -> list[int]: ...

    @property
    def finitecount(self) -> list[int]: ...

    @property
    def sum(self) -> list[float]: ...

    @property
    def sum2(self) -> list[float]: ...

class CompareResults:
    def __init__(self) -> None: ...

    @property
    def meanerror(self) -> float: ...

    @property
    def rms_error(self) -> float: ...

    @property
    def PSNR(self) -> float: ...

    @property
    def maxerror(self) -> float: ...

    @property
    def maxx(self) -> int: ...

    @property
    def maxy(self) -> int: ...

    @property
    def maxz(self) -> int: ...

    @property
    def maxc(self) -> int: ...

    @property
    def nwarn(self) -> int: ...

    @property
    def nfail(self) -> int: ...

    @property
    def error(self) -> bool: ...

class ImageBufAlgo:
    @overload
    @staticmethod
    def zero(dst: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def zero(roi: ROI, nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def fill(dst: ImageBuf, values: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def fill(dst: ImageBuf, top: float | typing.Iterable[float], bottom: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def fill(dst: ImageBuf, topleft: float | typing.Iterable[float], topright: float | typing.Iterable[float], bottomleft: float | typing.Iterable[float], bottomright: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def fill(values: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...
    @overload
    @staticmethod
    def fill(top: float | typing.Iterable[float], bottom: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...
    @overload
    @staticmethod
    def fill(topleft: float | typing.Iterable[float], topright: float | typing.Iterable[float], bottomleft: float | typing.Iterable[float], bottomright: float | typing.Iterable[float], roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def checker(dst: ImageBuf, width: int, height: int, depth: int, color1: object, color2: object, xoffset: int = 0, yoffset: int = 0, zoffset: int = 0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def checker(width: int, height: int, depth: int, color1: object, color2: object, xoffset: int = 0, yoffset: int = 0, zoffset: int = 0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def noise(dst: ImageBuf, type: str = 'gaussian', A: float = 0.0, B: float = 0.10000000149011612, mono: bool = False, seed: int = 0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def noise(type: str = 'gaussian', A: float = 0.0, B: float = 0.10000000149011612, mono: bool = False, seed: int = 0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @staticmethod
    def bluenoise_image() -> ImageBuf: ...

    @overload
    @staticmethod
    def channels(dst: ImageBuf, src: ImageBuf, channelorder: tuple, newchannelnames: tuple = (), shuffle_channel_names: bool = False, nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def channels(src: ImageBuf, channelorder: tuple, newchannelnames: tuple = (), shuffle_channel_names: bool = False, nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def channel_append(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def channel_append(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def deepen(dst: ImageBuf, src: ImageBuf, zvalue: float = 1.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def deepen(src: ImageBuf, zvalue: float = 1.0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def flatten(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def flatten(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def deep_merge(dst: ImageBuf, A: ImageBuf, B: ImageBuf, occlusion_cull: bool = True, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def deep_merge(A: ImageBuf, B: ImageBuf, occlusion_cull: bool = True, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def deep_holdout(dst: ImageBuf, src: ImageBuf, holdout: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def deep_holdout(src: ImageBuf, holdout: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def copy(dst: ImageBuf, src: ImageBuf, convert: TypeDesc | BASETYPE | str = ..., roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def copy(src: ImageBuf, convert: TypeDesc | BASETYPE | str = ..., roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def crop(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def crop(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def cut(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def cut(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @staticmethod
    def paste(dst: ImageBuf, xbegin: int, ybegin: int, zbegin: int, chbegin: int, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate90(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate90(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rotate180(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate180(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rotate270(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate270(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def flip(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def flip(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def flop(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def flop(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def reorient(dst: ImageBuf, src: ImageBuf, nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def reorient(src: ImageBuf, nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def transpose(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def transpose(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def circular_shift(dst: ImageBuf, src: ImageBuf, xshift: int, yshift: int, zshift: int = 0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def circular_shift(src: ImageBuf, xshift: int, yshift: int, zshift: int = 0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def add(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def add(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def add(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def add(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def sub(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def sub(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def sub(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def sub(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def absdiff(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def absdiff(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def absdiff(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def absdiff(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def abs(dst: ImageBuf, A: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def abs(A: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def scale(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def scale(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mul(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mul(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mul(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mul(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def div(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def div(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def div(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def div(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mad(dst: ImageBuf, A: ImageBuf, B: ImageBuf, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mad(dst: ImageBuf, A: ImageBuf, B: object, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mad(dst: ImageBuf, A: object, B: ImageBuf, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mad(dst: ImageBuf, A: ImageBuf, B: object, C: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def mad(A: ImageBuf, B: ImageBuf, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mad(A: ImageBuf, B: object, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mad(A: object, B: ImageBuf, C: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def mad(A: ImageBuf, B: object, C: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def invert(dst: ImageBuf, A: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def invert(A: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def pow(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def pow(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def channel_sum(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def channel_sum(dst: ImageBuf, src: ImageBuf, weight: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def channel_sum(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def channel_sum(src: ImageBuf, weight: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def color_map(dst: ImageBuf, src: ImageBuf, srcchannel: int, mapname: str, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def color_map(dst: ImageBuf, src: ImageBuf, srcchannel: int, nknots: int, channels: int, knots: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def color_map(src: ImageBuf, srcchannel: int, mapname: str, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def color_map(src: ImageBuf, srcchannel: int, nknots: int, channels: int, knots: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rangecompress(dst: ImageBuf, src: ImageBuf, useluma: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rangecompress(src: ImageBuf, useluma: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rangeexpand(dst: ImageBuf, src: ImageBuf, useluma: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rangeexpand(src: ImageBuf, useluma: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def premult(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def premult(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def unpremult(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def unpremult(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def repremult(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def repremult(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def min(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def min(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def min(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def min(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def max(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def max(dst: ImageBuf, A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def max(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def max(A: ImageBuf, B: object, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def clamp(dst: ImageBuf, src: ImageBuf, min: float | typing.Iterable[float], max: float | typing.Iterable[float], clampalpha01: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def clamp(src: ImageBuf, min: float | typing.Iterable[float], max: float | typing.Iterable[float], clampalpha01: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def maxchan(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def maxchan(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def minchan(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def minchan(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def contrast_remap(dst: ImageBuf, src: ImageBuf, black: float | typing.Iterable[float] = 0.0, white: float | typing.Iterable[float] = 1.0, min: float | typing.Iterable[float] = 0.0, max: float | typing.Iterable[float] = 1.0, scontrast: float | typing.Iterable[float] = 1.0, sthresh: float | typing.Iterable[float] = 0.5, roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def contrast_remap(src: ImageBuf, black: float | typing.Iterable[float] = 0.0, white: float | typing.Iterable[float] = 1.0, min: float | typing.Iterable[float] = 0.0, max: float | typing.Iterable[float] = 1.0, scontrast: float | typing.Iterable[float] = 1.0, sthresh: float | typing.Iterable[float] = 0.5, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def saturate(dst: ImageBuf, src: ImageBuf, scale: float = 0.0, firstchannel: int = 0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def saturate(src: ImageBuf, scale: float = 0.0, firstchannel: int = 0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def decorr_stretch(dst: ImageBuf, src: ImageBuf, firstchannel: int = 0, nchannels: int = 0, scale: float = 1.0, sigma: float = 0.0, mean: object | None = None, percentile: float = 0.0, mode: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def decorr_stretch(src: ImageBuf, firstchannel: int = 0, nchannels: int = 0, scale: float = 1.0, sigma: float = 0.0, mean: object | None = None, percentile: float = 0.0, mode: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def colorconvert(dst: ImageBuf, src: ImageBuf, fromspace: str, tospace: str, unpremult: bool = True, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def colorconvert(dst: ImageBuf, src: ImageBuf, fromspace: str, tospace: str, unpremult: bool = True, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def colorconvert(src: ImageBuf, fromspace: str, tospace: str, unpremult: bool = True, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def colorconvert(src: ImageBuf, fromspace: str, tospace: str, unpremult: bool = True, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def colormatrixtransform(dst: ImageBuf, src: ImageBuf, M: object, unpremult: bool = True, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def colormatrixtransform(src: ImageBuf, M: object, unpremult: bool = True, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociolook(dst: ImageBuf, src: ImageBuf, looks: str, fromspace: str, tospace: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociolook(dst: ImageBuf, src: ImageBuf, looks: str, fromspace: str, tospace: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociolook(src: ImageBuf, looks: str, fromspace: str, tospace: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociolook(src: ImageBuf, looks: str, fromspace: str, tospace: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociodisplay(dst: ImageBuf, src: ImageBuf, display: str, view: str, fromspace: str = '', looks: str = '', unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociodisplay(dst: ImageBuf, src: ImageBuf, display: str, view: str, fromspace: str = '', looks: str = '', unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociodisplay(src: ImageBuf, display: str, view: str, fromspace: str = '', looks: str = '', unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociodisplay(src: ImageBuf, display: str, view: str, fromspace: str = '', looks: str = '', unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociodisplay(dst: ImageBuf, src: ImageBuf, display: str, view: str, fromspace: str, looks: str, unpremult: bool, context_key: str, context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociodisplay(dst: ImageBuf, src: ImageBuf, display: str, view: str, fromspace: str, looks: str, unpremult: bool, context_key: str, context_value: str, colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociodisplay(src: ImageBuf, display: str, view: str, fromspace: str, looks: str, unpremult: bool, context_key: str, context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociodisplay(src: ImageBuf, display: str, view: str, fromspace: str, looks: str, unpremult: bool, context_key: str, context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociofiletransform(dst: ImageBuf, src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociofiletransform(dst: ImageBuf, src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ociofiletransform(src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ociofiletransform(src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ocionamedtransform(dst: ImageBuf, src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ocionamedtransform(dst: ImageBuf, src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ocionamedtransform(src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ocionamedtransform(src: ImageBuf, name: str, unpremult: bool = True, inverse: bool = False, context_key: str = '', context_value: str = '', colorconfig: str = '', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def computePixelStats(src: ImageBuf, stats: PixelStats, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def computePixelStats(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> PixelStats: ...

    @overload
    @staticmethod
    def compare(A: ImageBuf, B: ImageBuf, failthresh: float, warnthresh: float, result: CompareResults, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def compare(A: ImageBuf, B: ImageBuf, failthresh: float, warnthresh: float, failrelative: float = 0.0, warnrelative: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> CompareResults: ...

    @overload
    @staticmethod
    def compare(A: ImageBuf, B: ImageBuf, failthresh: float, warnthresh: float, roi: ROI = ..., nthreads: int = 0) -> CompareResults: ...

    @staticmethod
    def compare_Yee(A: ImageBuf, B: ImageBuf, result: CompareResults, luminance: float = 100, fov: float = 45, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def FLIP_diff(ref: ImageBuf, test: ImageBuf, hdr: int = 1, maxluminance: float = 2.0, medianluminance: float = 0.18000000715255737, ppd: float = 0.0, tonemapper: str = 'aces', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def FLIP_diff(dst: ImageBuf, ref: ImageBuf, test: ImageBuf, hdr: int = 1, maxluminance: float = 2.0, medianluminance: float = 0.18000000715255737, ppd: float = 0.0, tonemapper: str = 'aces', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @staticmethod
    def FLIP_ppd(monitor_distance_m: float = 0.699999988079071, screen_width_px: float = 3840.0, screen_width_m: float = 0.699999988079071) -> float: ...

    @staticmethod
    def isConstantColor(src: ImageBuf, threshold: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> tuple[float, ...] | None: ...

    @staticmethod
    def isConstantChannel(src: ImageBuf, channel: int, val: float, threshold: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @staticmethod
    def isMonochrome(src: ImageBuf, threshold: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @staticmethod
    def color_range_check(src: ImageBuf, low: object, high: object, roi: ROI = ..., nthreads: int = 0) -> tuple[int, ...] | None: ...

    @staticmethod
    def nonzero_region(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ROI: ...

    @staticmethod
    def computePixelHashSHA1(src: ImageBuf, extrainfo: str = '', roi: ROI = ..., blocksize: int = 0, nthreads: int = 0) -> str: ...

    @overload
    @staticmethod
    def warp(dst: ImageBuf, src: ImageBuf, M: object, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, wrap: str = 'default', roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def warp(src: ImageBuf, M: object, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, wrap: str = 'default', roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rotate(dst: ImageBuf, src: ImageBuf, angle: float, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate(dst: ImageBuf, src: ImageBuf, angle: float, center_x: float, center_y: float, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def rotate(src: ImageBuf, angle: float, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def rotate(src: ImageBuf, angle: float, center_x: float, center_y: float, filtername: str = '', filterwidth: float = 0.0, recompute_roi: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def resize(dst: ImageBuf, src: ImageBuf, filtername: str = '', filterwidth: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def resize(src: ImageBuf, filtername: str = '', filterwidth: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def resample(dst: ImageBuf, src: ImageBuf, interpolate: bool = True, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def resample(src: ImageBuf, interpolate: bool = True, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def st_warp(dst: ImageBuf, src: ImageBuf, stbuf: ImageBuf, filtername: str = '', filterwidth: float = 0.0, chan_s: int = 0, chan_t: int = 1, flip_s: bool = False, flip_t: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def st_warp(src: ImageBuf, stbuf: ImageBuf, filtername: str = '', filterwidth: float = 0.0, chan_s: int = 0, chan_t: int = 1, flip_s: bool = False, flip_t: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def fit(dst: ImageBuf, src: ImageBuf, filtername: str = '', filterwidth: float = 0.0, fillmode: str = 'letterbox', exact: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def fit(src: ImageBuf, filtername: str = '', filterwidth: float = 0.0, fillmode: str = 'letterbox', exact: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def make_kernel(dst: ImageBuf, name: str, width: float, height: float, depth: float = 1.0, normalize: bool = True) -> bool: ...

    @overload
    @staticmethod
    def make_kernel(name: str, width: float, height: float, depth: float = 1.0, normalize: bool = True) -> ImageBuf: ...

    @overload
    @staticmethod
    def convolve(dst: ImageBuf, src: ImageBuf, kernel: ImageBuf, normalze: bool = True, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def convolve(src: ImageBuf, kernel: ImageBuf, normalze: bool = True, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def unsharp_mask(dst: ImageBuf, src: ImageBuf, kernel: str = 'gaussian', width: float = 3.0, contrast: float = 1.0, threshold: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def unsharp_mask(src: ImageBuf, kernel: str = 'gaussian', width: float = 3.0, contrast: float = 1.0, threshold: float = 0.0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def median_filter(dst: ImageBuf, src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def median_filter(src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def dilate(dst: ImageBuf, src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def dilate(src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def erode(dst: ImageBuf, src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def erode(src: ImageBuf, width: int = 3, height: int = -1, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def laplacian(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def laplacian(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def fft(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def fft(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def ifft(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def ifft(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def polar_to_complex(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def polar_to_complex(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def complex_to_polar(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def complex_to_polar(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def fixNonFinite(dst: ImageBuf, src: ImageBuf, mode: NonFiniteFixMode = NonFiniteFixMode.NONFINITE_BOX3, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def fixNonFinite(src: ImageBuf, mode: NonFiniteFixMode = NonFiniteFixMode.NONFINITE_BOX3, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def normalize(dst: ImageBuf, src: ImageBuf, inCenter: float = 0.0, outCenter: float = 0.0, scale: float = 1.0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def normalize(src: ImageBuf, inCenter: float = 0.0, outCenter: float = 0.0, scale: float = 1.0, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def fillholes_pushpull(dst: ImageBuf, src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def fillholes_pushpull(src: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def over(dst: ImageBuf, A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def over(A: ImageBuf, B: ImageBuf, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @overload
    @staticmethod
    def zover(dst: ImageBuf, A: ImageBuf, B: ImageBuf, z_zeroisinf: bool = False, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @overload
    @staticmethod
    def zover(A: ImageBuf, B: ImageBuf, z_zeroisinf: bool = False, roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

    @staticmethod
    def render_point(dst: ImageBuf, x: int, y: int, color: float | typing.Iterable[float] = ...) -> bool: ...

    @staticmethod
    def render_line(dst: ImageBuf, x1: int, y1: int, x2: int, y2: int, color: float | typing.Iterable[float] = ..., skip_first_point: bool = False) -> bool: ...

    @staticmethod
    def render_box(dst: ImageBuf, x1: int, y1: int, x2: int, y2: int, color: float | typing.Iterable[float] = ..., fill: bool = False) -> bool: ...

    @staticmethod
    def render_text(dst: ImageBuf, x: int, y: int, text: str, fontsize: int = 16, fontname: str = '', textcolor: object = (), alignx: str = 'left', aligny: str = 'baseline', shadow: int = 0, roi: ROI = ..., nthreads: int = 0) -> bool: ...

    @staticmethod
    def text_size(text: str, fontsize: int = 16, fontname: str = '') -> ROI: ...

    @staticmethod
    def histogram(src: ImageBuf, channel: int = 0, bins: int = 256, min: float = 0.0, max: float = 1.0, ignore_empty: bool = False, roi: ROI = ..., nthreads: int = 0) -> tuple[int, ...]: ...

    @overload
    @staticmethod
    def make_texture(mode: MakeTextureMode, filename: str, outputfilename: str, config: ImageSpec = ...) -> bool: ...

    @overload
    @staticmethod
    def make_texture(mode: MakeTextureMode, buf: ImageBuf, outputfilename: str, config: ImageSpec = ...) -> bool: ...

    @overload
    @staticmethod
    def demosaic(dst: ImageBuf, src: ImageBuf, pattern: str = '', algorithm: str = '', layout: str = '', white_balance_mode: str = '', white_balance: float | typing.Iterable[float] = ..., roi: ROI = ..., nthreads: int = 0) -> bool: ...
    @overload
    @staticmethod
    def demosaic(src: ImageBuf, pattern: str = '', algorithm: str = '', layout: str = '', white_balance_mode: str = '', white_balance: float | typing.Iterable[float] = ..., roi: ROI = ..., nthreads: int = 0) -> ImageBuf: ...

@overload
def attribute(arg0: str, arg1: object, /) -> None: ...
@overload
def attribute(arg0: str, arg1: TypeDesc | BASETYPE | str, arg2: object, /) -> None: ...

def get_int_attribute(name: str, defaultval: int = 0) -> int: ...

def get_float_attribute(name: str, defaultval: float = 0.0) -> float: ...

def get_string_attribute(name: str, defaultval: str = '') -> str: ...

def getattribute(arg0: str, arg1: TypeDesc | BASETYPE | str, /) -> typing.Any: ...

def geterror(clear: bool = True) -> str: ...

def get_bytes_attribute(name: str, defaultval: object | None = '') -> bytes: ...

def set_colorspace(spec: ImageSpec, name: str) -> None: ...

def set_colorspace_rec709_gamma(spec: ImageSpec, gamma: float) -> None: ...

def is_colorspace_srgb(spec: ImageSpec, default_to_srgb: bool = True) -> bool: ...

def get_colorspace_icc_profile(spec: ImageSpec, from_colorspace: bool = True) -> bytes | None: ...

def get_colorspace_cicp(spec: ImageSpec, from_colorspace: bool = True) -> list[int] | None: ...

def equivalent_colorspace(a: str, b: str) -> bool: ...

def is_imageio_format_name(name: str) -> bool: ...

AutoStride: int = -9223372036854775808

openimageio_version: int = 30300

VERSION: int = 30300

VERSION_STRING: str = '3.3.0.0dev'

VERSION_MAJOR: int = 3

VERSION_MINOR: int = 3

VERSION_PATCH: int = 0

INTRO_STRING: str = ...
