# Copyright Contributors to the OpenImageIO project.
# SPDX-License-Identifier: Apache-2.0
# https://github.com/AcademySoftwareFoundation/OpenImageIO

######################################################################
# TIFF by hand!
######################################################################

set_cache (TIFF_BUILD_VERSION 4.7.1 "TIFF version for local builds")
set (TIFF_GIT_REPOSITORY "https://gitlab.com/libtiff/libtiff.git")
set_cache (TIFF_GIT_TAG "v${TIFF_BUILD_VERSION}" "Git branch or tag")
set_cache (TIFF_GIT_COMMIT "5fe20d0e9aba49a6a350ed533459d1505203838f"
           "commit hash to verify tag against")
set_cache (TIFF_BUILD_SHARED_LIBS  ${LOCAL_BUILD_SHARED_LIBS_DEFAULT}
           "Should a local TIFF build, if necessary, build shared libraries" ADVANCED)

# We need libdeflate to build libtiff
checked_find_package (libdeflate REQUIRED
                      VERSION_MIN 1.18)
alias_library_if_not_exists (Deflate::Deflate libdeflate::libdeflate_static)

# We need zstd to build libtiff with ZSTD compression
checked_find_package (zstd REQUIRED
                      VERSION_MIN 1.4)
alias_library_if_not_exists (ZSTD::ZSTD zstd::libzstd_static)
alias_library_if_not_exists (ZSTD::ZSTD zstd::libzstd_shared)

if (TARGET libjpeg-turbo::jpeg)
    # We've had some trouble with TIFF finding the JPEG resources it needs to
    # build if we're using libjpeg-turbo, TIFF needs an extra nudge.
    get_target_property(JPEG_INCLUDE_DIRS JPEG::JPEG INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(JPEG_LIBRARIES JPEG::JPEG INTERFACE_LINK_LIBRARIES)
    set (JPEG_FOUND TRUE)
    set (MORE_TIFF_CMAKE_ARGS
         -D JPEG_INCLUDE_DIR=${JPEG_INCLUDE_DIRS}
         -D JPEG_LIBRARY=${JPEG_LIBRARIES} )
endif ()

# libtiff's WEBP codec (for TIFF files using COMPRESSION_WEBP) needs libwebp,
# so search for it if we don't already have its target.
if (NOT TARGET WebP::webp)
    find_package (WebP CONFIG QUIET)
endif ()

# Left to itself, libtiff finds WebP with the FindWebP module it bundles, which
# locates a bare libwebp by path and ignores libwebp's own CMake package. That
# picks up whatever libwebp is visible in the environment, and drops the
# separate sharpyuv library that a static libwebp needs, so linking libtiff
# fails with undefined SharpYuv* symbols. Inject the package we found instead,
# so libtiff links exactly what we link.
if (TARGET WebP::webp AND WebP_DIR)
    set (TIFF_USE_WEBP ON)
    set (TIFF_WEBP_INJECT "${${PROJECT_NAME}_LOCAL_DEPS_ROOT}/TIFF-webp.cmake")
    file (WRITE "${TIFF_WEBP_INJECT}"
            "# Generated by OpenImageIO's build_TIFF.cmake -- do not edit.\n"
            "# Give libtiff the same WebP package OpenImageIO itself uses, so that its\n"
            "# bundled FindWebP module does not search for one on its own.\n"
            "find_package (WebP CONFIG REQUIRED PATHS \"${WebP_DIR}\" NO_DEFAULT_PATH)\n"
            "get_target_property (_webp_inc WebP::webp INTERFACE_INCLUDE_DIRECTORIES)\n"
            "get_target_property (_webp_lib WebP::webp IMPORTED_LOCATION_RELEASE)\n"
            "foreach (_cfg IMPORTED_LOCATION IMPORTED_LOCATION_NOCONFIG IMPORTED_LOCATION_DEBUG)\n"
            "    if (NOT _webp_lib)\n"
            "        get_target_property (_webp_lib WebP::webp \${_cfg})\n"
            "    endif ()\n"
            "endforeach ()\n"
            "# libtiff's FindWebP skips its own search when these are already set, and\n"
            "# leaves the WebP::webp target above alone.\n"
            "set (WebP_INCLUDE_DIR \"\${_webp_inc}\" CACHE PATH \"\" FORCE)\n"
            "set (WebP_LIBRARY \"\${_webp_lib}\" CACHE FILEPATH \"\" FORCE)\n"
            )
    list (APPEND MORE_TIFF_CMAKE_ARGS -D CMAKE_PROJECT_INCLUDE=${TIFF_WEBP_INJECT})
else ()
    set (TIFF_USE_WEBP OFF)
    message (STATUS "No WebP package found, local TIFF build will lack WEBP compression")
endif ()

# Hand libtiff the exact zstd library we found, so that its bundled FindZSTD
# module does not go looking on its own.
set (TIFF_USE_ZSTD OFF)
if (TARGET ZSTD::ZSTD)
    get_target_property (_zstd_inc ZSTD::ZSTD INTERFACE_INCLUDE_DIRECTORIES)
    foreach (_cfg IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_NOCONFIG
                  IMPORTED_LOCATION IMPORTED_LOCATION_DEBUG)
        if (NOT _zstd_lib)
            get_target_property (_zstd_lib ZSTD::ZSTD ${_cfg})
        endif ()
    endforeach ()
    if (_zstd_inc AND _zstd_lib)
        set (TIFF_USE_ZSTD ON)
        list (APPEND MORE_TIFF_CMAKE_ARGS
              -D ZSTD_INCLUDE_DIR=${_zstd_inc}
              -D ZSTD_LIBRARY=${_zstd_lib}
              # Skip libtiff's link test, which lacks the threads library
              # that a multithreaded static libzstd needs on older glibc.
              -D ZSTD_HAVE_DECOMPRESS_STREAM=ON )
    endif ()
    unset (_zstd_inc)
    unset (_zstd_lib)
endif ()
if (NOT TIFF_USE_ZSTD)
    message (STATUS "No zstd package found, local TIFF build will lack ZSTD compression")
endif ()

build_dependency_with_cmake(TIFF
    VERSION         ${TIFF_BUILD_VERSION}
    GIT_REPOSITORY  ${TIFF_GIT_REPOSITORY}
    GIT_TAG         ${TIFF_GIT_TAG}
    GIT_COMMIT      ${TIFF_GIT_COMMIT}
    CMAKE_ARGS
        -D BUILD_SHARED_LIBS=${TIFF_BUILD_SHARED_LIBS}
        -D CMAKE_POSITION_INDEPENDENT_CODE=ON
        -D CMAKE_INSTALL_LIBDIR=lib
        -D tiff-tools=OFF
        -D tiff-contrib=OFF
        -D tiff-tests=OFF
        -D tiff-docs=OFF
        -D libdeflate=ON
        -D lzma=OFF
        -D zstd=${TIFF_USE_ZSTD}
        -D jbig=OFF
        -D lerc=OFF
        -D webp=${TIFF_USE_WEBP}
        ${MORE_TIFF_CMAKE_ARGS}
    )

# Signal to caller that we need to find again at the installed location
set (TIFF_REFIND TRUE)
set (TIFF_REFIND_VERSION ${TIFF_BUILD_VERSION})

if (TIFF_BUILD_SHARED_LIBS)
    install_local_dependency_libs (TIFF TIFF)
endif ()

unset (MORE_TIFF_CMAKE_ARGS)
unset (TIFF_USE_WEBP)
unset (TIFF_USE_ZSTD)
