version: 2
jobs:
  avx2:
    docker:
      - image: debian:stretch
    environment:
      - USE_SIMD: avx2,fma,f16c
    steps:
      - checkout
      - run: |
            source src/build-scripts/ci-startup.bash
            source src/build-scripts/circleci-installdeps.bash
            source src/build-scripts/ci-build-and-test.bash
  avx512:
    docker:
      - image: debian:stretch
    environment:
      - USE_SIMD: avx512f,avx512dq,avx512cd,avx512bw,avx512vl,fma,f16c
    steps:
      - checkout
      - run: |
            source src/build-scripts/ci-startup.bash
            source src/build-scripts/circleci-installdeps.bash
            source src/build-scripts/ci-build-and-test.bash


workflows:
  version: 2
  # Kick off parallel jobs for each build configuration.
  all:
    jobs:
      - avx2
      - avx512
