if (NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL_NAME)
    message (FATAL_ERROR
             "embed_binary_header.cmake requires INPUT, OUTPUT, and SYMBOL_NAME")
endif ()

get_filename_component (_embed_output_dir "${OUTPUT}" DIRECTORY)
file (MAKE_DIRECTORY "${_embed_output_dir}")
file (READ "${INPUT}" _embed_hex HEX)
string (LENGTH "${_embed_hex}" _embed_hex_length)
if (_embed_hex_length EQUAL 0)
    message (FATAL_ERROR "binary input '${INPUT}' is empty")
endif ()

math (EXPR _embed_remainder "${_embed_hex_length} % 2")
if (NOT _embed_remainder EQUAL 0)
    message (FATAL_ERROR
             "binary input '${INPUT}' has invalid size ${_embed_hex_length}")
endif ()

math (EXPR _embed_byte_count "${_embed_hex_length} / 2")
math (EXPR _embed_last_index "${_embed_byte_count} - 1")

file (WRITE "${OUTPUT}" "// Generated by embed_binary_header.cmake. Do not edit.\n")
file (APPEND "${OUTPUT}" "#pragma once\n\n")
file (APPEND "${OUTPUT}" "#include <cstddef>\n")
file (APPEND "${OUTPUT}" "#include <cstdint>\n\n")
file (APPEND "${OUTPUT}" "namespace Imiv {\n\n")
file (APPEND "${OUTPUT}" "static const unsigned char ${SYMBOL_NAME}[] = {\n")

set (_embed_line "    ")
set (_embed_items_on_line 0)
foreach (_embed_byte_index RANGE 0 ${_embed_last_index})
    math (EXPR _embed_offset "${_embed_byte_index} * 2")
    string (SUBSTRING "${_embed_hex}" ${_embed_offset} 2 _embed_byte)

    string (APPEND _embed_line "0x${_embed_byte}")
    if (NOT _embed_byte_index EQUAL _embed_last_index)
        string (APPEND _embed_line ", ")
    endif ()

    math (EXPR _embed_items_on_line "${_embed_items_on_line} + 1")
    if (_embed_items_on_line EQUAL 12 OR _embed_byte_index EQUAL _embed_last_index)
        string (APPEND _embed_line "\n")
        file (APPEND "${OUTPUT}" "${_embed_line}")
        set (_embed_line "    ")
        set (_embed_items_on_line 0)
    endif ()
endforeach ()

file (APPEND "${OUTPUT}" "};\n")
file (APPEND "${OUTPUT}"
      "static constexpr std::size_t ${SYMBOL_NAME}_size = sizeof(${SYMBOL_NAME});\n\n")
file (APPEND "${OUTPUT}" "}  // namespace Imiv\n")
