if (NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL_NAME)
    message (FATAL_ERROR
             "embed_spirv_header.cmake requires INPUT, OUTPUT, and SYMBOL_NAME")
endif ()

get_filename_component (_embed_output_dir "${OUTPUT}" DIRECTORY)
file (MAKE_DIRECTORY "${_embed_output_dir}")
file (READ "${INPUT}" _embed_hex HEX)
string (LENGTH "${_embed_hex}" _embed_hex_length)
if (_embed_hex_length EQUAL 0)
    message (FATAL_ERROR "SPIR-V input '${INPUT}' is empty")
endif ()

math (EXPR _embed_remainder "${_embed_hex_length} % 8")
if (NOT _embed_remainder EQUAL 0)
    message (FATAL_ERROR
             "SPIR-V input '${INPUT}' has invalid size ${_embed_hex_length}")
endif ()

math (EXPR _embed_word_count "${_embed_hex_length} / 8")
math (EXPR _embed_last_index "${_embed_word_count} - 1")

file (WRITE "${OUTPUT}" "// Generated by embed_spirv_header.cmake. Do not edit.\n")
file (APPEND "${OUTPUT}" "#pragma once\n\n")
file (APPEND "${OUTPUT}" "#include <cstddef>\n")
file (APPEND "${OUTPUT}" "#include <cstdint>\n\n")
file (APPEND "${OUTPUT}" "namespace Imiv {\n\n")
file (APPEND "${OUTPUT}" "static const uint32_t ${SYMBOL_NAME}[] = {\n")

set (_embed_line "    ")
set (_embed_items_on_line 0)
foreach (_embed_word_index RANGE 0 ${_embed_last_index})
    math (EXPR _embed_offset "${_embed_word_index} * 8")
    math (EXPR _embed_offset_1 "${_embed_offset} + 2")
    math (EXPR _embed_offset_2 "${_embed_offset} + 4")
    math (EXPR _embed_offset_3 "${_embed_offset} + 6")
    string (SUBSTRING "${_embed_hex}" ${_embed_offset} 2 _embed_b0)
    string (SUBSTRING "${_embed_hex}" ${_embed_offset_1} 2 _embed_b1)
    string (SUBSTRING "${_embed_hex}" ${_embed_offset_2} 2 _embed_b2)
    string (SUBSTRING "${_embed_hex}" ${_embed_offset_3} 2 _embed_b3)

    string (APPEND _embed_line
            "0x${_embed_b3}${_embed_b2}${_embed_b1}${_embed_b0}u")
    if (NOT _embed_word_index EQUAL _embed_last_index)
        string (APPEND _embed_line ", ")
    endif ()

    math (EXPR _embed_items_on_line "${_embed_items_on_line} + 1")
    if (_embed_items_on_line EQUAL 4 OR _embed_word_index EQUAL _embed_last_index)
        string (APPEND _embed_line "\n")
        file (APPEND "${OUTPUT}" "${_embed_line}")
        set (_embed_line "    ")
        set (_embed_items_on_line 0)
    endif ()
endforeach ()

file (APPEND "${OUTPUT}" "};\n")
file (APPEND "${OUTPUT}"
      "static constexpr std::size_t ${SYMBOL_NAME}_word_count = sizeof(${SYMBOL_NAME}) / sizeof(${SYMBOL_NAME}[0]);\n\n")
file (APPEND "${OUTPUT}" "}  // namespace Imiv\n")
